import { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: [ "latin" ] });

export const metadata = {
  manifest: "/manifest.json",
  title: "MyD Quest",
  description: "Generated by BHN Corp.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full bg-gray-200">
      <body className={inter.className} >{children}</body>
    </html>
  );
}
