import { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: [ "latin" ] });

export const metadata = {
  manifest: "/manifest.json",
  title: "MyD Quest",
  description: "Generated by BHN Corp.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" class="h-full">
      <body class="h-full" className={inter.className}>{children}</body>
    </html>
  );
}
